In [1]:
import pickle
import numpy as np
import torch
import matplotlib.pyplot as plt

In [4]:
import pickle

import numpy as np
import torch

import dataloader
import sim_config

val_size = 100
test_size = 1000

data_config = sim_config.DataConfig(n_sample=1000 + val_size + test_size)
n_sample = data_config.n_sample

action_dim = data_config.action_dim
t_max = data_config.t_max
step_size = data_config.step_size
sparsity = data_config.sparsity
p_remove = data_config.p_remove

output_sigma = 0.2
dose_max = 10

# on averaga three latents contribute to a measurement

# dim 8
output_sparsity = 1 - 0.375
latent_dim = 8
obs_dim = 40
roche_config = sim_config.RochConfig(kel=1)

seed = 666
np.random.seed(seed)
torch.manual_seed(seed)

device = torch.device("cpu")

dg = dataloader.DataGeneratorRoche(
    n_sample,
    obs_dim,
    t_max,
    step_size,
    roche_config,
    output_sigma,
    dose_max,
    latent_dim,
    sparsity,
    p_remove=p_remove,
    output_sparsity=output_sparsity,
    device=device,
    val_size=val_size,
    test_size=test_size,
)
dg.generate_data()
dg.split_sample()


with open("data/datafile_dim8.pkl", "wb") as f:
    pickle.dump(dg, f)

In [2]:
with open('data/datafile_dose_noise_1.0.pkl', "rb") as f:
    data = pickle.load(f)

In [6]:
data.latents.shape

torch.Size([15, 2100, 6])

In [43]:
# for i in range(data.measurements.shape[-1]):
#     plt.plot(data.measurements[:, 0, i])
#     plt.title(f"measurement {i}")
#     plt.show()

In [31]:
# data.actions[:, 0, :]
torch.max(data.actions[..., 0], dim=0)[0].shape
# for i in range(15):
#     plt.figure(figsize=(10, 5))
#     plt.hist(data.actions[i, :, 0], bins=20)
#     plt.show()
#     plt.clf()

torch.Size([2100])

In [44]:
data

In [36]:
for i in range(data.actions.shape[1]):
    print(torch.where(data.actions[..., 0][:, i] != 0)[0])

tensor([10])
tensor([10])
tensor([8])
tensor([2])
tensor([3])
tensor([1])
tensor([8])
tensor([0])
tensor([6])
tensor([13])
tensor([5])
tensor([1])
tensor([10])
tensor([13])
tensor([4])
tensor([3])
tensor([8])
tensor([5])
tensor([2])
tensor([8])
tensor([0])
tensor([10])
tensor([3])
tensor([12])
tensor([1])
tensor([2])
tensor([5])
tensor([5])
tensor([10])
tensor([11])
tensor([6])
tensor([8])
tensor([3])
tensor([2])
tensor([1])
tensor([12])
tensor([3])
tensor([8])
tensor([7])
tensor([10])
tensor([7])
tensor([7])
tensor([4])
tensor([12])
tensor([0])
tensor([4])
tensor([6])
tensor([3])
tensor([10])
tensor([5])
tensor([6])
tensor([0])
tensor([1])
tensor([8])
tensor([12])
tensor([8])
tensor([13])
tensor([10])
tensor([10])
tensor([3])
tensor([11])
tensor([1])
tensor([6])
tensor([9])
tensor([10])
tensor([7])
tensor([6])
tensor([3])
tensor([8])
tensor([13])
tensor([12])
tensor([12])
tensor([12])
tensor([9])
tensor([7])
tensor([8])
tensor([13])
tensor([5])
tensor([9])
tensor([7])
tensor([7])
tens